// Executive team members
const executives = [
    {
        first_name: "Prajeethreddy",
        last_name: "Bhuma",
        email: "prajeethreddy.bhuma@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/prajeethreddybhuma/",
        position: "President",
        headshot: "/members/prajeethreddy-bhuma.jpg",
    },
    {
        first_name: "Akshara",
        last_name: "Akella",
        email: "akshara.akella@consultyourcommunity.org",
        major: "Business Administration",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/akshara-akella/",
        position: "VP of Growth & Partnerships",
        headshot: "/members/akshara-akella.jpg",
    },
    {
        first_name: "Unaiza",
        last_name: "Khakoo",
        email: "Unaiza.khakoo@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/unaizakhakoo/",
        position: "VP of Finance",
        headshot: "/members/unaiza-khakoo.jpeg",
    },
    {
        first_name: "Arnav",
        last_name: "Prabhu",
        email: "Arnav.Prabhu@consultyourcommunity.org",
        major: "Business Analytics",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/arnavprabhu/",
        position: "VP of Tech & Marketing",
        headshot: "/members/arnav-prabhu.jpg",
    },
    {
        first_name: "Rushil",
        last_name: "Kannery",
        email: "rushil.kannery@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/rushilkannery/",
        position: "VP of Client Relations",
        headshot: "/members/rushil-kannery.jpg",
    },
    {
        first_name: "Anas",
        last_name: "Hassan",
        email: "anas.hassan@consultyourcommunity.org",
        major: "Business Analytics",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/anas-hassan/",
        position: "VP of Consulting",
        headshot: "/members/anas-hassan.jpg",
    },
];

const senior_analysts = [
    {
        first_name: "Varsha",
        last_name: "Janumpally",
        email: "varsha.janumpally@consultyourcommunity.org",
        major: "Information Technology",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/varsha-janumpally/",
        headshot: "/members/varsha-janumpally.jpeg",
    },
    {
        first_name: "Arnay",
        last_name: "Majumdar",
        email: "arnay.majumdar@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/arnay-majumdar/",
        headshot: "/members/arnay-majumdar.jpeg",
    },
    {
        first_name: "Ayaan",
        last_name: "Ahmed",
        email: "ayaan.ahmed@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2029,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/ayaan-ahmed.jpg",
    },
    {
        first_name: "Jeslin",
        last_name: "Mathew",
        email: "jeslin.mathew@consultyourcommunity.org",
        major: "Supply Chain Management",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/jeslinlizmathew/",
        headshot: "/members/jeslin-matthew.jpeg",
    },
    {
        first_name: "Kushagra",
        last_name: "Bharti",
        email: "kushagra.bharti@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/kushagra-bharti/",
        headshot: "/members/kushagra-bharti.jpeg",
    },
    {
        first_name: "Satwik",
        last_name: "Padhy",
        email: "satwik.padhy@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/satwik-yash-padhy/",
        headshot: "/members/satwik-padhy.jpg",
    },
    {
        first_name: "Pranav",
        last_name: "Boyapati",
        email: "pranav.boyapati@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/pranav-boyapati/",
        headshot: "/members/pranav-boyapati.jpg",
    },
    {
        first_name: "Ashna",
        last_name: "Murali",
        email: "test@gmail.com",
        major: "Business",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/placeholder.jpg",
    },
    {
        first_name: "Mahbube",
        last_name: "Rabbani",
        email: "mahbube.rabbani@consultyourcommunity.org",
        major: "MS in BUAN",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/placeholder.jpg",
    },
    {
        first_name: "Rithik",
        last_name: "Chowdam",
        email: "rithik.chowdam@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/rithik-chowdam.jpg",
    },
];

// Junior analyst team members
const junior_analysts = [
    {
        first_name: "Yuvraj",
        last_name: "Kashyap",
        email: "yuvraj.kashyap@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/yuvraj-kashyap.jpg",
    },
    {
        first_name: "Muhammad",
        last_name: "Meetheen",
        email: "muhammad.meetheen@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/placeholder.jpg",
    },
    {
        first_name: "Pranishka",
        last_name: "Jagtap",
        email: "pranishka.jagtap@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2029,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/pranishka-jagtap.jpg",
    },
    {
        first_name: "Adrian",
        last_name: "Perez Sanchez",
        email: "adrian.perezsanchez@consultyourcommunity.org",
        major: "CISTech",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/placeholder.jpg",
    },
    {
        first_name: "Manisha",
        last_name: "Mishra",
        email: "manisha.mishra@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/placeholder.jpg",
    },
    {
        first_name: "Suhaas",
        last_name: "Gaddala",
        email: "suhaas.gaddala@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/placeholder.jpg",
    },
    {
        first_name: "Hansini",
        last_name: "Routhu",
        email: "hansini.routhu@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2029,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/hansini-routhu.jpg",
    },
    {
        first_name: "Sri Samanyu",
        last_name: "Sagiraju",
        email: "srisamanyu.sagiraju@consultyourcommunity.org",
        major: "BUAN",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/sri-sagiraju.jpg",
    },
    {
        first_name: "Aydin",
        last_name: "Mahmood",
        email: "aydin.mahmood@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/aydin-mahmood.jpg",
    },
    {
        first_name: "Likhitsaish",
        last_name: "Kadiam",
        email: "likhitsaish.kadiam@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2029,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/likhitsaish-kadiam.jpg",
    },
    {
        first_name: "Sri Supraja",
        last_name: "Vishnubhatla",
        email: "srisupraja.vishnubhatla@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/srisupraja-vishnubhatla.jpg",
    },
    {
        first_name: "Rakeen",
        last_name: "Virani",
        email: "rakeen.virani@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/rakeen-virani.jpg",
    },
];

export { executives, senior_analysts, junior_analysts };
