// Executive team members
const executives = [
    {
        first_name: "Prajeethreddy",
        last_name: "Bhuma",
        email: "prajeethreddy.bhuma@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/prajeethreddybhuma/",
        position: "President",
        headshot: "/members/prajeethreddy-bhuma.jpg",
    },
    {
        first_name: "Akshara",
        last_name: "Akella",
        email: "akshara.akella@consultyourcommunity.org",
        major: "Business Administration",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/akshara-akella/",
        position: "VP of Growth & Partnerships",
        headshot: "/members/akshara-akella.jpg",
    },
    {
        first_name: "Arnav",
        last_name: "Prabhu",
        email: "Arnav.Prabhu@consultyourcommunity.org",
        major: "Business Analytics",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/arnavprabhu/",
        position: "VP of Tech & Marketing",
        headshot: "/members/arnav-prabhu.jpg",
    },
    {
        first_name: "Anas",
        last_name: "Hassan",
        email: "anas.hassan@consultyourcommunity.org",
        major: "Business Analytics",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/anas-hassan/",
        position: "VP of Consulting",
        headshot: "/members/anas-hassan.jpg",
    },
    {
        first_name: "Rushil",
        last_name: "Kannery",
        email: "rushil.kannery@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/rushilkannery/",
        position: "Co-VP of Consulting",
        headshot: "/members/rushil-kannery.jpg",
    },
    {
        first_name: "Ayaan",
        last_name: "Ahmed",
        email: "ayaan.ahmed@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2029,
        linkedin: "https://www.linkedin.com/in/",
        position: "VP of Client Relations",
        headshot: "/members/ayaan-ahmed.jpg",
    },
];

const senior_analysts = [
    {
        first_name: "Pranav",
        last_name: "Boyapati",
        email: "pranav.boyapati@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/pranav-boyapati/",
        headshot: "/members/pranav-boyapati.jpg",
    },
    {
        first_name: "Yuvraj",
        last_name: "Kashyap",
        email: "yuvraj.kashyap@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/yuvraj-kashyap.jpg",
    },
    {
        first_name: "Pranishka",
        last_name: "Jagtap",
        email: "pranishka.jagtap@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2029,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/pranishka-jagtap.jpg",
    },
    {
        first_name: "Hansini",
        last_name: "Routhu",
        email: "hansini.routhu@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2029,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/hansini-routhu.jpg",
    },
    {
        first_name: "Aydin",
        last_name: "Mahmood",
        email: "aydin.mahmood@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/aydin-mahmood.jpg",
    },
    {
        first_name: "Sri Supraja",
        last_name: "Vishnubhatla",
        email: "srisupraja.vishnubhatla@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/srisupraja-vishnubhatla.jpg",
    },
    {
        first_name: "Rakeen",
        last_name: "Virani",
        email: "rakeen.virani@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/rakeen-virani.jpg",
    },
];

// Junior analyst team members
const junior_analysts = [
    {
        first_name: "Aakriti",
        last_name: "Ramakrishnan",
        email: "aakriti.ramakrishnan@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/placeholder.jpg",
    },
];

export { executives, senior_analysts, junior_analysts };
